sabrinagheissari/fitpass310

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

add navbar and footer to application.html.erb

adding navbar and footer to layout

---

app/controllers/bookings_controller.rb
app/controllers/sessions_controller.rb
app/controllers/studios_controller.rb
config/routes.rb
test/controllers/bookings_controller_test.rb
test/controllers/sessions_controller_test.rb
test/controllers/studios_controller_test.rb

Created all controller actions + routes

Added controller actions and routes

---

app/models/session.rb
app/models/user.rb
db/seeds.rb

I created our foundational seeds

seeds created

---

.gitignore
Gemfile
Gemfile.lock
app/models/studio.rb
app/uploaders/photo_uploader.rb
db/migrate/20191112061445_add_photo_to_studios.rb
db/schema.rb

I have added details for Cloudinary and have added the photo column to the table studios.

Added cloudinary details and photo column to Studios

---

app/controllers/bookings_controller.rb

Added the create, delete methods for booking.

Added controller methods for booking

---

app/assets/stylesheets/components/_btn_booking.scss
app/assets/stylesheets/components/_card_booking.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_colors.scss
app/views/sessions/show.html.erb

did the html of the show page session
did a bit of css

show page of sessions: html ok and first style CSS

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/controllers/studios_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/models/studio.rb
app/views/layouts/application.html.erb
app/views/studios/_info_window.html.erb
app/views/studios/index.html.erb
config/initializers/geocoder.rb
db/migrate/20191113034602_add_coordinates_to_studios.rb
db/schema.rb
db/seeds.rb
package.json
yarn.lock

Created the map function for studios.

Added map functionality

---

app/assets/stylesheets/pages/_studio.scss
app/views/studios/index.html.erb
db/migrate/20191113052953_remove_time_from_courses.rb
db/migrate/20191113053016_add_time_to_courses.rb
db/schema.rb
db/seeds.rb

studios done

---

app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Added links to navbar and default search

Added links to navbar and default search

---

app/views/shared/_navbar.html.erb

Added home for navbar

---

app/assets/stylesheets/pages/_studio.scss
app/views/studios/index.html.erb
db/seeds.rb

css change

---

app/controllers/courses_controller.rb
app/controllers/pages_controller.rb
app/controllers/studios_controller.rb

Added fixes for skipping login

Added fixes for skipping login for studios show

---

app/assets/stylesheets/components/_button_studio.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_layout_buttons_studio.scss
app/views/studios/show.html.erb
db/seeds.rb

This pull-request is concerning the changes in the style of the Studio page:
Color
Variables like the photos
Displaying Time in a better way
Capacity and other attributes for the studio...

Studio page style

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/views/bookings/index.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/shared/_navbar.html.erb
package-lock.json
package.json
yarn.lock

Added user default picture and sweetalert for confirmation

Added user default picture and sweetalert

---

app/assets/stylesheets/components/_button_review.scss
app/assets/stylesheets/components/_button_studio.scss
app/views/studios/show.html.erb

font change

---

app/javascript/packs/application.js
app/views/bookings/index.html.erb

2 files which were missed in the last commit

2 files which were missed in the last commit

---

app/assets/stylesheets/components/_button_studio.scss
app/views/studios/show.html.erb

color of the rose button

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/pages/_studio.scss
app/views/studios/index.html.erb
db/seeds.rb

finalized the css for the studio index page. only thing left is to change the booking button.

Rewriting seeds

---

app/assets/stylesheets/components/_button_studio.scss
app/views/studios/show.html.erb

Please pull this is the last one

Studio page button ok

---

app/assets/stylesheets/components/_button_review.scss

delete white blackground

---

app/javascript/packs/application.js

Changed color of sweet alert

---

app/views/pages/home.html.erb
db/seeds.rb

time updated

---

app/assets/stylesheets/components/_layout_buttons_studio.scss
app/views/studios/show.html.erb

The position of buttons is fixed now.

Fixed buttons responsively

---

app/controllers/studios_controller.rb
app/models/studio.rb
app/views/studios/index.html.erb

Added filters

---

app/controllers/reviews_controller.rb
app/models/course.rb
app/models/review.rb
app/models/user.rb
app/views/bookings/_card.html.erb
app/views/reviews/new.html.erb
config/routes.rb
db/migrate/20191115032209_create_reviews.rb
db/schema.rb
test/controllers/reviews_controller_test.rb
test/models/review_test.rb

Reviews backend
